/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedPestsRouteImport } from './routes/_authenticated/pests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBedsBedIdRouteImport } from './routes/_authenticated/beds/$bedId'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedLibrarySlugRouteImport } from './routes/_authenticated/library/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPestsRoute = AuthenticatedPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedsBedIdRoute = AuthenticatedBedsBedIdRouteImport.update({
  id: '/beds/$bedId',
  path: '/beds/$bedId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibrarySlugRoute =
  AuthenticatedLibrarySlugRouteImport.update({
    id: '/library/$slug',
    path: '/library/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/log': typeof AuthenticatedLogRoute
  '/map': typeof AuthenticatedMapRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/beds/$bedId': typeof AuthenticatedBedsBedIdRoute
  '/library/$slug': typeof AuthenticatedLibrarySlugRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/log': typeof AuthenticatedLogRoute
  '/map': typeof AuthenticatedMapRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/beds/$bedId': typeof AuthenticatedBedsBedIdRoute
  '/library/$slug': typeof AuthenticatedLibrarySlugRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/pests': typeof AuthenticatedPestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/beds/$bedId': typeof AuthenticatedBedsBedIdRoute
  '/_authenticated/library/$slug': typeof AuthenticatedLibrarySlugRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/log'
    | '/map'
    | '/pests'
    | '/settings'
    | '/beds/$bedId'
    | '/library/$slug'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/log'
    | '/map'
    | '/pests'
    | '/settings'
    | '/beds/$bedId'
    | '/library/$slug'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/log'
    | '/_authenticated/map'
    | '/_authenticated/pests'
    | '/_authenticated/settings'
    | '/_authenticated/beds/$bedId'
    | '/_authenticated/library/$slug'
    | '/_authenticated/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pests': {
      id: '/_authenticated/pests'
      path: '/pests'
      fullPath: '/pests'
      preLoaderRoute: typeof AuthenticatedPestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beds/$bedId': {
      id: '/_authenticated/beds/$bedId'
      path: '/beds/$bedId'
      fullPath: '/beds/$bedId'
      preLoaderRoute: typeof AuthenticatedBedsBedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$slug': {
      id: '/_authenticated/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof AuthenticatedLibrarySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPestsRoute: typeof AuthenticatedPestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBedsBedIdRoute: typeof AuthenticatedBedsBedIdRoute
  AuthenticatedLibrarySlugRoute: typeof AuthenticatedLibrarySlugRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPestsRoute: AuthenticatedPestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBedsBedIdRoute: AuthenticatedBedsBedIdRoute,
  AuthenticatedLibrarySlugRoute: AuthenticatedLibrarySlugRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
